elasticsearch:
  uris: ${ELASTICSEARCH_URIS}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  host: ${KEYCLOAK_HOST}
  realm: ${KEYCLOAK_REALM}

rest-client:
  keycloak:
    read-timeout: 1_000