cache:
  type: simple

elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

keycloak:
  client-id: fc3-app
  client-secret: seecret
  host: "http://localhost:${wiremock.server.port:8001}"
  realm: test

logging:
  level:
    ROOT: info

rest-client:
  base-url: "http://localhost:${wiremock.server.port:8001}"
  categories:
    read-timeout: 300
  keycloak:
    read-timeout: 300

resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 1

resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 2
      permittedNumberOfCallsInHalfOpenState: 1
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 300

resilience4j.retry:
  configs:
    default:
      maxAttempts: 2
      waitDuration: 100